require "rmeetup/type/topic"
require "rmeetup/type/group"
require "rmeetup/type/city"
require "rmeetup/type/member"
require "rmeetup/type/rsvp"
require "rmeetup/type/event"
require "rmeetup/type/comment"
require "rmeetup/type/photo"